lesson_6 not done
ivanmolchanov1988/geekshop pull request #7
Opened 2021-02-10 18:19 UTC by ivanmolchanov1988

Добрый день!

У меня не работает ajax :(
Я не понимаю, что не так. 
Ошибоки не возвращает, странички загружаются, вроде всё ок, всё пересмотрел, ничего не понимаю.

Помогите разобраться, пожалуйста.

Спасибо за урок!

2021-02-10 18:56 UTC, Vokler requested changes

2021-02-10 18:56 UTC, Vokler commented on authapp/templates/authapp/profile.html
> +    <script>src="{% static 'js/basket.js' %}"</script>
Обратите внимание, где у вас находится атрибут src

2021-02-10 18:56 UTC, Vokler commented on basket/urls.py
> +    path('edit/<int:id>/<int:quantity/>', basket_edit, name='basket_edit'),
Обратите внимание на то, где у вас находится последний слеш.
Вот здесь - `<int:quantity/>`

2021-02-10 18:56 UTC, Vokler commented on static/js/basket.js
> +            url: "/baskets/edit/" + t_href.name + "/" + t_href.value + "/"
Здесь запятую забыли в конце строки

2021-02-11 09:23 UTC, ivanmolchanov1988 commented on authapp/templates/authapp/profile.html
> +    <script>src="{% static 'js/basket.js' %}"</script>
Спасибо! Всё исправил.

2021-02-11 09:24 UTC, ivanmolchanov1988 commented on basket/urls.py
> +    path('edit/<int:id>/<int:quantity/>', basket_edit, name='basket_edit'),
Исправил.

2021-02-11 09:24 UTC, ivanmolchanov1988 commented on static/js/basket.js
> +            url: "/baskets/edit/" + t_href.name + "/" + t_href.value + "/"
Исправил.

2021-02-11 15:28 UTC, merged